# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Slideshow

# Model Form Field configuration
form: $/borzoi/slideshow/models/slideshow/fields.yaml

# Model Class name
modelClass: Borzoi\SlideShow\Models\SlideShow

# Default redirect location
defaultRedirect: borzoi/slideshow/slideshows

# Create page
create:
    title: Create Slideshow
    redirect: borzoi/slideshow/slideshows/update/:id
    redirectClose: borzoi/slideshow/slideshows

# Update page
update:
    title: Edit Slideshow
    redirect: borzoi/slideshow/slideshows
    redirectClose: borzoi/slideshow/slideshows

# Preview page
preview:
    title: Preview Slideshow
